# Generated by Django 5.2.6 on 2025-09-19 12:06

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('photo', models.ImageField(default='images/default.png', upload_to=api.models.rename_photo)),
            ],
        ),
    ]
