# Generated by Django 5.2.6 on 2025-09-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='static/images/default.png', upload_to='static/images/'),
        ),
    ]
