# Generated by Django 5.2.6 on 2025-09-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_employee_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(default='images/default.png', upload_to='images/'),
        ),
    ]
