# Generated by Django 5.2.6 on 2025-09-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_employee_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
    ]
