"""add total_price column to orders

Revision ID: 8400f4306011
Revises: 
Create Date: 2025-09-12 10:46:43.748615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8400f4306011'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('total_price', sa.Float(), nullable=True))
    op.alter_column('parent_orders', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               nullable=False,
               autoincrement=True)
    op.alter_column('parent_orders', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_index(op.f('ix_parent_orders_index'), table_name='parent_orders')
    op.drop_column('parent_orders', 'index')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parent_orders', sa.Column('index', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_parent_orders_index'), 'parent_orders', ['index'], unique=False)
    op.alter_column('parent_orders', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('parent_orders', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               nullable=True,
               autoincrement=True)
    op.drop_column('orders', 'total_price')
    # ### end Alembic commands ###
